export {
  bootstrapBridge,
  createBootEvent,
  createPageReadyEvent,
  createPingEvent,
  type BridgeBootstrapHandle,
  type BridgeBootstrapOptions,
  type BridgeBootstrapPort,
} from "./bridge/bootstrap";
export {
  createSelectionExplanationCompletedEvent,
  createSelectionExplanationFailedEvent,
  createSelectionRequestedEvent,
  type SelectionEventMetadata,
} from "./bridge/selection-events";
export {
  deriveSelectionKind,
  extractSelectionContext,
  type ExtractSelectionOptions,
  type SelectionDocumentLike,
  type SelectionElementLike,
  type SelectionLike,
  type SelectionNodeLike,
  type SelectionRangeLike,
} from "./dom/selection-context";
export {
  createTranslationCompletedEvent,
  createTranslationFailedEvent,
  createTranslationRequestedEvent,
  type TranslationEventMetadata,
} from "./bridge/translation-events";
export {
  createPageContext,
  deriveStableSegmentId,
  normalizeSegmentText,
  scanPageSegments,
  type ScanPageOptions,
  type ScanPageResult,
  type ScannerDocument,
  type ScannerElement,
  type ScannerTextNode,
} from "./dom/segment-scanner";
export {
  applyOverlayState,
  applyTranslationResult,
  messageForFailure,
  OVERLAY_STATUS_LABELS,
  type OverlayDocumentLike,
  type OverlayElementLike,
  type OverlaySegmentState,
} from "./overlay/translation-overlay";
export {
  DISPLAY_MODE_LABELS,
  DisplayModeController,
  isTextReadingModeAllowed,
  type DisplayModeContext,
} from "./modes/display-mode-controller";
export {
  detectSiteAdapter,
  AO3_SITE_CAPABILITIES,
  GENERIC_SITE_PROFILE,
  REDDIT_SITE_CAPABILITIES,
  WIKIPEDIA_SITE_CAPABILITIES,
  X_SITE_CAPABILITIES,
  isAO3URL,
  isRedditURL,
  isWikipediaURL,
  isXURL,
  type SiteAdapterProfile,
} from "./site-adapters";
export {
  buildJson3CaptionUrl,
  captionLineSignature,
  createYouTubeVideoCaptionState,
  detectYouTubePage,
  findActiveCaptionLine,
  isAutoGeneratedCaptionTrack,
  isYouTubeSiteUrl,
  parseCaptionTracks,
  parseJson3Captions,
  readActiveYouTubeCaptionText,
  selectCaptionTrack,
  youtubePageCapabilities,
  type CreateYouTubeVideoCaptionStateOptions,
  type SelectCaptionTrackOptions,
  type YouTubeCaptionDocumentLike,
  type YouTubeCaptionLine,
  type YouTubeCaptionTrack,
  type YouTubeJson3Payload,
  type YouTubePageDetection,
  type YouTubePlayerResponseLike,
} from "./site-adapters/youtube";
export {
  createYouTubeAudioTranslationState,
  decideYouTubeAudioTranslationSource,
  type YouTubeAudioTranslationDecision,
  type YouTubeAudioTranslationDecisionInput,
} from "./site-adapters/youtube-audio";
export {
  VIDEO_CAPTION_FALLBACK_ID,
  VIDEO_CAPTION_OVERLAY_ID,
  VIDEO_CAPTION_STATUS_LABELS,
  VIDEO_AUDIO_STATUS_LABELS,
  applyVideoCaptionOverlayState,
  messageForVideoAudioFailure,
  messageForVideoCaptionFailure,
  type VideoCaptionOverlayDocumentLike,
  type VideoCaptionOverlayElementLike,
} from "./overlay/video-caption-overlay";
export { BROWSER_AGENT_RUNTIME_SOURCE } from "./browser-runtime-source";
