// Phase 8.9：YouTube 视频自带字幕轨数据读取 + 解析 + 按播放进度时间同步的纯逻辑层。
//
// 设计依据（ADR-0004 v2.8 / ARCHITECTURE v2.8）：
// - 字幕来源从「渲染 DOM（.ytp-caption-segment）」改为「视频自带字幕轨数据」——读
//   `getPlayerResponse()` / `ytInitialPlayerResponse` 的
//   `.captions.playerCaptionsTracklistRenderer.captionTracks`，选轨后同源 fetch
//   `baseUrl + "&fmt=json3"` 解析为带时间轴的字幕句序列，再按 `video.currentTime` 定位当前句。
// - 字幕轨数据读取 / 解析 / 选轨 / 时间同步只在 browser-agent；不持翻译 key、不直连模型。
// - 合规：只在内存中保留当前视频解析结果，不写文件 / 不离线缓存整轨 / 不再分发；本模块为纯
//   函数，不做任何 IO（fetch 由注入侧同源发起，本模块只解析其返回）。
//
// 本文件是「逻辑层」：纯函数 + 类型，可被 .mjs 单测直接断言（不出网）。注入运行时
// （runtime-source/youtube-caption-track-source.ts）在 WKWebView 页面上下文内实现等价逻辑。

/**
 * YouTube player response 中 `captionTracks[]` 的单条字幕轨（仅取本 Phase 用到的字段）。
 * `kind === "asr"` 表示自动生成（语音识别）轨；人工轨无 `kind` 或 `kind !== "asr"`。
 */
export interface YouTubeCaptionTrack {
  baseUrl: string;
  languageCode?: string;
  kind?: string;
  name?: { simpleText?: string } | string;
  vssId?: string;
}

/**
 * player response 的最小结构契约（只声明本 Phase 读取路径，避免对 YouTube 内部结构过拟合）。
 */
export interface YouTubePlayerResponseLike {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: YouTubeCaptionTrack[];
    };
  };
}

/**
 * json3（`fmt=json3`）payload 的最小结构契约。
 * events[].segs[].utf8 拼接成一句，tStartMs / dDurationMs 给出时间轴（毫秒）。
 */
export interface YouTubeJson3Segment {
  utf8?: string;
}

export interface YouTubeJson3Event {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: YouTubeJson3Segment[];
}

export interface YouTubeJson3Payload {
  events?: YouTubeJson3Event[];
}

/**
 * 解析后的一句字幕（带时间轴，单位秒）。下游填充 `VideoCaptionSegment.startTimeSeconds /
 * endTimeSeconds / sourceText`。
 */
export interface YouTubeCaptionLine {
  startTimeSeconds: number;
  endTimeSeconds: number;
  sourceText: string;
}

export interface SelectCaptionTrackOptions {
  /** 用户学习语言上下文（如 "en" / "zh-Hans"）；未注入时退化为「英文 → ASR」。 */
  targetLanguageCode?: string;
}

/**
 * 从 player response 提取 captionTracks。无 captions / 空轨 → 返回空数组（不抛异常）。
 */
export function parseCaptionTracks(
  playerResponse: YouTubePlayerResponseLike | null | undefined,
): YouTubeCaptionTrack[] {
  const tracks =
    playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!Array.isArray(tracks)) {
    return [];
  }

  return tracks.filter(
    (track): track is YouTubeCaptionTrack =>
      typeof track?.baseUrl === "string" && track.baseUrl.length > 0,
  );
}

function isAutoGeneratedTrack(track: YouTubeCaptionTrack): boolean {
  if (track.kind === "asr") {
    return true;
  }
  return typeof track.vssId === "string" && track.vssId.startsWith("a.");
}

function languageMatches(
  track: YouTubeCaptionTrack,
  languagePrefix: string,
): boolean {
  const code = track.languageCode?.toLowerCase() ?? "";
  return code === languagePrefix || code.startsWith(`${languagePrefix}-`);
}

/**
 * 选轨优先级：英文人工轨 > 目标语言人工轨 > 英文 ASR > 目标语言 ASR > 任意人工轨 > 任意轨。
 * 目标语言上下文缺省时退化为「英文人工 → 英文 ASR → 任意人工 → 任意轨」。
 * 无可用轨 → 返回 null（下游降级 captionAvailability=unavailable）。
 */
export function selectCaptionTrack(
  tracks: readonly YouTubeCaptionTrack[],
  options: SelectCaptionTrackOptions = {},
): YouTubeCaptionTrack | null {
  if (tracks.length === 0) {
    return null;
  }

  const manualTracks = tracks.filter((track) => !isAutoGeneratedTrack(track));
  const target = options.targetLanguageCode?.toLowerCase();

  const englishManual = manualTracks.find((track) =>
    languageMatches(track, "en"),
  );
  if (englishManual) {
    return englishManual;
  }

  if (target && target !== "en") {
    const targetManual = manualTracks.find((track) =>
      languageMatches(track, target),
    );
    if (targetManual) {
      return targetManual;
    }
  }

  const englishAuto = tracks.find(
    (track) => isAutoGeneratedTrack(track) && languageMatches(track, "en"),
  );
  if (englishAuto) {
    return englishAuto;
  }

  if (target && target !== "en") {
    const targetAuto = tracks.find(
      (track) => isAutoGeneratedTrack(track) && languageMatches(track, target),
    );
    if (targetAuto) {
      return targetAuto;
    }
  }

  return manualTracks[0] ?? tracks[0] ?? null;
}

/** 选中轨是否为自动生成 / ASR 轨（供下游标识 selectedTrackIsAutoGenerated）。 */
export function isAutoGeneratedCaptionTrack(
  track: YouTubeCaptionTrack,
): boolean {
  return isAutoGeneratedTrack(track);
}

/**
 * 在 baseUrl 上追加 `&fmt=json3`（baseUrl 已带 query，故用 `&`）。幂等：已含 fmt=json3 不重复加。
 */
export function buildJson3CaptionUrl(baseUrl: string): string {
  if (/[?&]fmt=json3(&|$)/.test(baseUrl)) {
    return baseUrl;
  }
  const separator = baseUrl.includes("?") ? "&" : "?";
  return `${baseUrl}${separator}fmt=json3`;
}

function normalizeLineText(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

/**
 * 把 json3 payload 解析为带时间轴的字幕句序列（按 startTimeSeconds 升序）。
 * - 每句 startTimeSeconds = tStartMs / 1000，endTimeSeconds = (tStartMs + dDurationMs) / 1000。
 * - 空 segs / 纯换行 / 拼接后无可见文本的 event 被过滤。
 * - 不做任何缓存 / 持久化（合规：只取当前播放所需）。
 */
export function parseJson3Captions(
  payload: YouTubeJson3Payload | null | undefined,
): YouTubeCaptionLine[] {
  const events = payload?.events;
  if (!Array.isArray(events)) {
    return [];
  }

  const lines: YouTubeCaptionLine[] = [];
  for (const event of events) {
    if (typeof event?.tStartMs !== "number") {
      continue;
    }
    const segs = Array.isArray(event.segs) ? event.segs : [];
    const joined = segs.map((seg) => seg?.utf8 ?? "").join("");
    const sourceText = normalizeLineText(joined);
    if (sourceText.length === 0) {
      continue;
    }
    const startTimeSeconds = event.tStartMs / 1000;
    const durationMs =
      typeof event.dDurationMs === "number" ? event.dDurationMs : 0;
    const endTimeSeconds = (event.tStartMs + durationMs) / 1000;
    lines.push({ startTimeSeconds, endTimeSeconds, sourceText });
  }

  lines.sort((left, right) => left.startTimeSeconds - right.startTimeSeconds);
  return lines;
}

/**
 * 按 `currentTime`（秒）在已解析字幕句序列中定位当前句。区间为左闭右开 `[start, end)`。
 * 命中多句时取 startTimeSeconds 最大（最贴近当前播放点）的一句；无命中返回 null。
 */
export function findActiveCaptionLine(
  lines: readonly YouTubeCaptionLine[],
  currentTime: number,
): YouTubeCaptionLine | null {
  let active: YouTubeCaptionLine | null = null;
  for (const line of lines) {
    if (currentTime < line.startTimeSeconds) {
      continue;
    }
    if (currentTime >= line.endTimeSeconds) {
      continue;
    }
    if (!active || line.startTimeSeconds > active.startTimeSeconds) {
      active = line;
    }
  }
  return active;
}

/**
 * 当前句去重签名（sourceText + startTimeSeconds）；与 lastVideoCaptionSignature 比较，相同句
 * 不重复 post / 不重复翻译。无当前句时返回空串。
 */
export function captionLineSignature(
  line: YouTubeCaptionLine | null,
): string {
  if (!line) {
    return "";
  }
  return `${line.startTimeSeconds.toFixed(3)}:${line.sourceText}`;
}
