// Phase 8.9：YouTube 视频自带字幕轨数据读取 + 解析 + 按播放进度时间同步的纯逻辑层。
//
// 设计依据（ADR-0004 v2.8 / ARCHITECTURE v2.8；真机修订）：
// - 字幕来源从「渲染 DOM（.ytp-caption-segment）」改为「视频自带字幕轨数据」——取
//   `.captions.playerCaptionsTracklistRenderer.captionTracks`，选轨后同源 fetch json3 解析为带
//   时间轴的字幕句序列，再按 `video.currentTime` 定位当前句。
// - player response 获取优先 InnerTube `/youtubei/v1/player`（ANDROID client，按 URL videoId 重取，
//   见 buildInnerTubePlayerRequest）；移动版 m.youtube.com / Shorts / SPA 下 `getPlayerResponse()`
//   不可用、`ytInitialPlayerResponse` 不随路由更新，故仅作桌面场景兜底。
// - 字幕轨数据读取 / 解析 / 选轨 / 时间同步只在 browser-agent；不持翻译 key、不直连模型。
// - 合规：只在内存中保留当前视频解析结果，不写文件 / 不离线缓存整轨 / 不再分发；本模块为纯
//   函数，不做任何 IO（fetch 由注入侧同源发起，本模块只解析其返回）。
//
// 本文件是「逻辑层」：纯函数 + 类型，可被 .mjs 单测直接断言（不出网）。注入运行时
// （runtime-source/youtube-caption-track-source.ts）在 WKWebView 页面上下文内实现等价逻辑。

/**
 * YouTube player response 中 `captionTracks[]` 的单条字幕轨（仅取本 Phase 用到的字段）。
 * `kind === "asr"` 表示自动生成（语音识别）轨；人工轨无 `kind` 或 `kind !== "asr"`。
 */
export interface YouTubeCaptionTrack {
  baseUrl: string;
  languageCode?: string;
  kind?: string;
  name?: { simpleText?: string } | string;
  vssId?: string;
}

/**
 * player response 的最小结构契约（只声明本 Phase 读取路径，避免对 YouTube 内部结构过拟合）。
 */
export interface YouTubePlayerResponseLike {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: YouTubeCaptionTrack[];
    };
  };
}

/**
 * json3（`fmt=json3`）payload 的最小结构契约。
 * events[].segs[].utf8 拼接成一句，tStartMs / dDurationMs 给出时间轴（毫秒）。
 */
export interface YouTubeJson3Segment {
  utf8?: string;
}

export interface YouTubeJson3Event {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: YouTubeJson3Segment[];
}

export interface YouTubeJson3Payload {
  events?: YouTubeJson3Event[];
}

/**
 * 解析后的一句字幕（带时间轴，单位秒）。下游填充 `VideoCaptionSegment.startTimeSeconds /
 * endTimeSeconds / sourceText`。
 */
export interface YouTubeCaptionLine {
  startTimeSeconds: number;
  endTimeSeconds: number;
  sourceText: string;
}

export interface SelectCaptionTrackOptions {
  /** 用户学习语言上下文（如 "en" / "zh-Hans"）；未注入时退化为「英文 → ASR」。 */
  targetLanguageCode?: string;
}

/**
 * 从 player response 提取 captionTracks。无 captions / 空轨 → 返回空数组（不抛异常）。
 */
export function parseCaptionTracks(
  playerResponse: YouTubePlayerResponseLike | null | undefined,
): YouTubeCaptionTrack[] {
  const tracks =
    playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!Array.isArray(tracks)) {
    return [];
  }

  return tracks.filter(
    (track): track is YouTubeCaptionTrack =>
      typeof track?.baseUrl === "string" && track.baseUrl.length > 0,
  );
}

function isAutoGeneratedTrack(track: YouTubeCaptionTrack): boolean {
  if (track.kind === "asr") {
    return true;
  }
  return typeof track.vssId === "string" && track.vssId.startsWith("a.");
}

function languageMatches(
  track: YouTubeCaptionTrack,
  languagePrefix: string,
): boolean {
  const code = track.languageCode?.toLowerCase() ?? "";
  return code === languagePrefix || code.startsWith(`${languagePrefix}-`);
}

/**
 * 选轨优先级：英文人工轨 > 目标语言人工轨 > 英文 ASR > 目标语言 ASR > 任意人工轨 > 任意轨。
 * 目标语言上下文缺省时退化为「英文人工 → 英文 ASR → 任意人工 → 任意轨」。
 * 无可用轨 → 返回 null（下游降级 captionAvailability=unavailable）。
 */
export function selectCaptionTrack(
  tracks: readonly YouTubeCaptionTrack[],
  options: SelectCaptionTrackOptions = {},
): YouTubeCaptionTrack | null {
  if (tracks.length === 0) {
    return null;
  }

  const manualTracks = tracks.filter((track) => !isAutoGeneratedTrack(track));
  const target = options.targetLanguageCode?.toLowerCase();

  const englishManual = manualTracks.find((track) =>
    languageMatches(track, "en"),
  );
  if (englishManual) {
    return englishManual;
  }

  if (target && target !== "en") {
    const targetManual = manualTracks.find((track) =>
      languageMatches(track, target),
    );
    if (targetManual) {
      return targetManual;
    }
  }

  const englishAuto = tracks.find(
    (track) => isAutoGeneratedTrack(track) && languageMatches(track, "en"),
  );
  if (englishAuto) {
    return englishAuto;
  }

  if (target && target !== "en") {
    const targetAuto = tracks.find(
      (track) => isAutoGeneratedTrack(track) && languageMatches(track, target),
    );
    if (targetAuto) {
      return targetAuto;
    }
  }

  return manualTracks[0] ?? tracks[0] ?? null;
}

/** 选中轨是否为自动生成 / ASR 轨（供下游标识 selectedTrackIsAutoGenerated）。 */
export function isAutoGeneratedCaptionTrack(
  track: YouTubeCaptionTrack,
): boolean {
  return isAutoGeneratedTrack(track);
}

/**
 * 把 timedtext baseUrl 规整为请求 json3 格式的 URL。
 *
 * 先清掉 baseUrl 里已有的 `fmt=xxx`（部分来源的 baseUrl 带 `&fmt=srv3` 等），再追加
 * `&fmt=json3`。否则出现重复 `fmt` 参数时 YouTube 取第一个，导致返回 XML（`<timedtext>`）
 * 而非 json3 —— 真机验证踩过这个坑。
 */
export function buildJson3CaptionUrl(baseUrl: string): string {
  const withoutFmt = baseUrl
    .replace(/([?&])fmt=[^&]*&?/g, "$1")
    .replace(/[?&]$/, "");
  const separator = withoutFmt.includes("?") ? "&" : "?";
  return `${withoutFmt}${separator}fmt=json3`;
}

/**
 * InnerTube `/youtubei/v1/player` 请求（ANDROID client）。注入运行时据此在 YouTube 页面上下文
 * 同源 POST 取当前视频 player response；本纯函数只构造 URL 与 body，不出网。
 *
 * 为什么用 ANDROID client + 按 videoId 重取（ADR-0004 v2.8 修订 / 真机 curl 验证）：
 * - iOS WKWebView 未设 customUserAgent → 加载移动版 m.youtube.com，其播放器无
 *   `getPlayerResponse()`；Shorts/SPA 前端路由切换后 `ytInitialPlayerResponse` 不更新，
 *   导致读不到「当前视频」字幕轨。
 * - InnerTube 只需 URL 中的 videoId，不依赖播放器 DOM 就绪/更新，天然覆盖移动版 + Shorts + SPA。
 * - 实测：WEB client 受反爬返回 0 条 captionTracks；ANDROID client 可取（同视频 6 条）。key 非必需。
 */
export interface InnerTubePlayerRequest {
  url: string;
  body: string;
}

export function buildInnerTubePlayerRequest(
  videoId: string,
  apiKey?: string,
): InnerTubePlayerRequest {
  const url = apiKey
    ? `/youtubei/v1/player?key=${encodeURIComponent(apiKey)}`
    : "/youtubei/v1/player";
  const body = JSON.stringify({
    context: {
      client: {
        clientName: "ANDROID",
        clientVersion: "20.10.38",
        androidSdkVersion: 31,
        hl: "en",
        gl: "US",
      },
    },
    videoId,
  });
  return { url, body };
}

function normalizeLineText(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

/**
 * 把 json3 payload 解析为带时间轴的字幕句序列（按 startTimeSeconds 升序）。
 * - 每句 startTimeSeconds = tStartMs / 1000，endTimeSeconds = (tStartMs + dDurationMs) / 1000。
 * - 空 segs / 纯换行 / 拼接后无可见文本的 event 被过滤。
 * - 不做任何缓存 / 持久化（合规：只取当前播放所需）。
 */
export function parseJson3Captions(
  payload: YouTubeJson3Payload | null | undefined,
): YouTubeCaptionLine[] {
  const events = payload?.events;
  if (!Array.isArray(events)) {
    return [];
  }

  const lines: YouTubeCaptionLine[] = [];
  for (const event of events) {
    if (typeof event?.tStartMs !== "number") {
      continue;
    }
    const segs = Array.isArray(event.segs) ? event.segs : [];
    const joined = segs.map((seg) => seg?.utf8 ?? "").join("");
    const sourceText = normalizeLineText(joined);
    if (sourceText.length === 0) {
      continue;
    }
    const startTimeSeconds = event.tStartMs / 1000;
    const durationMs =
      typeof event.dDurationMs === "number" ? event.dDurationMs : 0;
    const endTimeSeconds = (event.tStartMs + durationMs) / 1000;
    lines.push({ startTimeSeconds, endTimeSeconds, sourceText });
  }

  lines.sort((left, right) => left.startTimeSeconds - right.startTimeSeconds);
  return lines;
}

const SENTENCE_MERGE_GAP_SECONDS = 1.2;
const SENTENCE_MERGE_MAX_CHARS = 140;
const SENTENCE_TERMINAL_PATTERN = /[.!?…。！？][)\]"'”’]*$/;
const SPEAKER_CHANGE_PATTERN = /^[-–—♪>»]/;

/**
 * 把 cue 级字幕片段按原始时间序合并为完整句（修「每句话不全」）：json3 的 cue 是按
 * 显示时间切的片段而非完整句，逐片段显示 / 翻译会让中英文都断在半截。
 * 断句条件（任一命中即闭合当前句）：
 * - 片段以句末标点结尾（允许尾随引号 / 括号）——人工轨标准断句；
 * - 与下一片段时间间隔 > 1.2 秒（说话停顿即句界）——兜底无标点的 ASR 自动轨；
 * - 合并长度将超 140 字符——防字幕叠层盒过高（极长句保护）；
 * - 下一片段以对白换行符 / 音乐符开头（- – — ♪ 等）——不同说话人不粘成一句。
 * 另：跳过与组尾相同的连续重复片段（ASR 滚动窗会重复上一片段文本）。
 * 合并句时间范围 = 首片段 start → 末片段 end（整句自首片段起完整显示，字幕略前于语音）。
 */
export function mergeCaptionLinesIntoSentences(
  lines: readonly YouTubeCaptionLine[],
): YouTubeCaptionLine[] {
  const merged: YouTubeCaptionLine[] = [];
  let group: YouTubeCaptionLine | null = null;
  let lastFragmentText = "";

  for (const line of lines) {
    if (group) {
      const gapSeconds = line.startTimeSeconds - group.endTimeSeconds;
      const wouldOverflow =
        group.sourceText.length + 1 + line.sourceText.length > SENTENCE_MERGE_MAX_CHARS;
      if (
        gapSeconds > SENTENCE_MERGE_GAP_SECONDS
        || wouldOverflow
        || SPEAKER_CHANGE_PATTERN.test(line.sourceText)
      ) {
        merged.push(group);
        group = null;
      }
    }

    if (group) {
      if (line.sourceText !== lastFragmentText) {
        group.sourceText += ` ${line.sourceText}`;
        lastFragmentText = line.sourceText;
      }
      group.endTimeSeconds = Math.max(group.endTimeSeconds, line.endTimeSeconds);
    } else {
      group = { ...line };
      lastFragmentText = line.sourceText;
    }

    if (SENTENCE_TERMINAL_PATTERN.test(group.sourceText)) {
      merged.push(group);
      group = null;
      lastFragmentText = "";
    }
  }
  if (group) {
    merged.push(group);
  }
  return merged;
}

/**
 * 按 `currentTime`（秒）在已解析字幕句序列中定位当前句。区间为左闭右开 `[start, end)`。
 * 命中多句时取 startTimeSeconds 最大（最贴近当前播放点）的一句；无命中返回 null。
 */
export function findActiveCaptionLine(
  lines: readonly YouTubeCaptionLine[],
  currentTime: number,
): YouTubeCaptionLine | null {
  let active: YouTubeCaptionLine | null = null;
  for (const line of lines) {
    if (currentTime < line.startTimeSeconds) {
      continue;
    }
    if (currentTime >= line.endTimeSeconds) {
      continue;
    }
    if (!active || line.startTimeSeconds > active.startTimeSeconds) {
      active = line;
    }
  }
  return active;
}

/**
 * 当前句去重签名（sourceText + startTimeSeconds）；与 lastVideoCaptionSignature 比较，相同句
 * 不重复 post / 不重复翻译。无当前句时返回空串。
 */
export function captionLineSignature(
  line: YouTubeCaptionLine | null,
): string {
  if (!line) {
    return "";
  }
  return `${line.startTimeSeconds.toFixed(3)}:${line.sourceText}`;
}
