export const gameStatements = [
  `CREATE TABLE IF NOT EXISTS dungeons (
    id TEXT PRIMARY KEY,
    story_lesson_id TEXT NOT NULL REFERENCES story_lessons(id) ON DELETE CASCADE,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    level TEXT NOT NULL,
    tag TEXT NOT NULL,
    xp_reward INTEGER NOT NULL,
    progress_percent INTEGER NOT NULL,
    tone TEXT NOT NULL,
    map_top TEXT NOT NULL,
    map_left TEXT NOT NULL,
    region TEXT NOT NULL,
    status TEXT NOT NULL,
    objective_text TEXT NOT NULL,
    monster_name TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS dungeons_status_idx ON dungeons (status)`,
  `CREATE TABLE IF NOT EXISTS battle_sessions (
    id TEXT PRIMARY KEY,
    dungeon_id TEXT NOT NULL REFERENCES dungeons(id) ON DELETE CASCADE,
    status TEXT NOT NULL,
    rescue_count INTEGER NOT NULL,
    current_round INTEGER NOT NULL,
    total_rounds INTEGER NOT NULL,
    hp_remaining INTEGER NOT NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS battle_sessions_dungeon_idx ON battle_sessions (dungeon_id)`,
  `CREATE TABLE IF NOT EXISTS battle_turns (
    id TEXT PRIMARY KEY,
    battle_session_id TEXT NOT NULL REFERENCES battle_sessions(id) ON DELETE CASCADE,
    turn_order INTEGER NOT NULL,
    user_answer TEXT NOT NULL,
    ai_feedback_json TEXT NOT NULL,
    hp_delta INTEGER NOT NULL,
    passed INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(battle_session_id, turn_order)
  )`,
  `CREATE TABLE IF NOT EXISTS saved_expressions (
    id TEXT PRIMARY KEY,
    story_lesson_id TEXT REFERENCES story_lessons(id) ON DELETE SET NULL,
    battle_turn_id TEXT REFERENCES battle_turns(id) ON DELETE SET NULL,
    expression TEXT NOT NULL,
    meaning_zh TEXT NOT NULL,
    source_text TEXT NOT NULL,
    status TEXT NOT NULL,
    used_count INTEGER NOT NULL,
    next_review_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS saved_expressions_status_idx ON saved_expressions (status)`,
  `CREATE TABLE IF NOT EXISTS expression_equipment (
    id TEXT PRIMARY KEY,
    saved_expression_id TEXT NOT NULL REFERENCES saved_expressions(id) ON DELETE CASCADE,
    equipment_name TEXT NOT NULL,
    rarity TEXT NOT NULL,
    use_count INTEGER NOT NULL,
    equipped INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS review_triggers (
    id TEXT PRIMARY KEY,
    saved_expression_id TEXT REFERENCES saved_expressions(id) ON DELETE SET NULL,
    battle_turn_id TEXT REFERENCES battle_turns(id) ON DELETE SET NULL,
    trigger_type TEXT NOT NULL,
    skill_key TEXT NOT NULL,
    stuck_count INTEGER NOT NULL,
    suggested_action TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS review_triggers_status_idx ON review_triggers (status)`,
  `CREATE TABLE IF NOT EXISTS boss_training_items (
    id TEXT PRIMARY KEY,
    review_trigger_id TEXT NOT NULL REFERENCES review_triggers(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    prompt TEXT NOT NULL,
    status TEXT NOT NULL,
    due_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS learning_records (
    id TEXT PRIMARY KEY,
    story_lesson_id TEXT REFERENCES story_lessons(id) ON DELETE SET NULL,
    battle_session_id TEXT REFERENCES battle_sessions(id) ON DELETE SET NULL,
    record_type TEXT NOT NULL,
    reward_key TEXT NOT NULL UNIQUE,
    xp_delta INTEGER NOT NULL,
    metadata_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS user_progress (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL UNIQUE,
    level INTEGER NOT NULL,
    xp INTEGER NOT NULL,
    streak_days INTEGER NOT NULL,
    skill_progress_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`
];
