export const RUNTIME_YOUTUBE_INJECTION_SOURCE = String.raw`  const readActiveYouTubeCaptionText = () => {
    // Phase 8.9：字幕轨来源优先——视频自带字幕轨已解析出当前句时直接用（不读渲染 DOM）；
    // 字幕轨不可用时回退 .ytp-caption-segment DOM 兜底（保留以做降级 / 旧路径兼容）。
    if (Array.isArray(videoCaptionLines) && videoCaptionLines.length) {
      const video = document.querySelector("video");
      const currentTime = video && typeof video.currentTime === "number" ? video.currentTime : 0;
      const line = findActiveCaptionLine(videoCaptionLines, currentTime);
      if (line) {
        return line.sourceText;
      }
    }
    const primaryNodes = Array.from(document.querySelectorAll(".ytp-caption-segment"));
    const fallbackNodes = primaryNodes.length
      ? primaryNodes
      : Array.from(document.querySelectorAll(".caption-window, .ytp-caption-window-container"));
    return normalizeText(fallbackNodes.map((node) => node.textContent || "").join(" "));
  };
  const buildYouTubeVideoCaptionState = (overrides = {}) => {
    const detection = detectYouTubePage();
    if (!detection.isVideoPage || !detection.pageKind) {
      return null;
    }
    const updatedAt = new Date().toISOString();
    const sourceText = normalizeText(
      typeof overrides.sourceText === "string" ? overrides.sourceText : readActiveYouTubeCaptionText(),
    );
    const hasCaption = sourceText.length > 0;
    const fromTrack = typeof overrides.containerPath === "string" && overrides.containerPath === "caption-track";
    const segment = hasCaption ? {
      pageId,
      segmentId: hashSeed("vcap", pageId + ":" + sourceText + ":" + updatedAt.slice(0, 19)),
      videoId: detection.videoId,
      sourceText,
      translatedText: overrides.translatedText,
      sourceLanguage: overrides.sourceLanguage || "English",
      targetLanguage: overrides.targetLanguage || "简体中文",
      startTimeSeconds: typeof overrides.startTimeSeconds === "number" ? overrides.startTimeSeconds : undefined,
      endTimeSeconds: typeof overrides.endTimeSeconds === "number" ? overrides.endTimeSeconds : undefined,
      selectedTrackLanguage: fromTrack ? overrides.selectedTrackLanguage : undefined,
      selectedTrackIsAutoGenerated: fromTrack ? Boolean(overrides.selectedTrackIsAutoGenerated) : undefined,
      containerPath: overrides.containerPath || ".ytp-caption-segment",
      capturedAt: updatedAt,
    } : undefined;
    return {
      pageId,
      siteKind: "youtube",
      pageKind: detection.pageKind,
      url: window.location.href,
      title: document.title || "",
      videoId: detection.videoId,
      captionAvailability: hasCaption ? "available" : "unavailable",
      overlayMode: overrides.overlayMode || (hasCaption ? "inline-overlay" : "fallback-bar"),
      status: overrides.status || (hasCaption ? "caption-available" : "caption-unavailable"),
      capabilities: hasCaption
        ? ["captions-available", "video-caption-overlay", "audio-translation-beta", "selection-fallback"]
        : ["captions-unavailable", "video-caption-fallback", "audio-translation-beta", "video-audio-translation", "selection-fallback"],
      activeSegment: segment,
      failureReason: overrides.failureReason || (hasCaption ? undefined : "caption-unavailable"),
      message: overrides.message || (hasCaption ? undefined : "当前视频没有检测到可用字幕。"),
      updatedAt,
    };
  };
  const postVideoCaptionState = (state, force = false) => {
    if (!state) {
      return false;
    }
    const signature = [
      state.pageKind,
      state.videoId || "",
      state.status,
      state.activeSegment?.sourceText || "",
      state.activeSegment?.translatedText || "",
      state.failureReason || "",
    ].join(":");
    if (!force && signature === lastVideoCaptionSignature) {
      return false;
    }
    lastVideoCaptionSignature = signature;
    applyVideoCaptionOverlayState(state);
    postBridgeEvent("video.caption.state.changed", state, {
      requestId: "video-caption-state-" + (state.activeSegment?.segmentId || sessionId),
      pageId,
    });
    return true;
  };
  const buildYouTubeVideoAudioState = (overrides = {}) => {
    const detection = detectYouTubePage();
    if (!detection.isVideoPage || !detection.pageKind) {
      return null;
    }
    const updatedAt = new Date().toISOString();
    const captionText = normalizeText(overrides.captionText || readActiveYouTubeCaptionText());
    const captionQuality = overrides.captionQuality || (captionText ? "available" : "unavailable");
    const captionAvailable = captionQuality === "available" || captionQuality === "low";
    const source = overrides.source || (
      overrides.manualAudioSelection || captionQuality === "low" || !captionText
        ? "audio"
        : "caption"
    );
    const audioSegmentId = overrides.audioSegmentId || hashSeed("vaud", pageId + ":audio:" + updatedAt.slice(0, 19));
    return {
      pageId,
      siteKind: "youtube",
      pageKind: detection.pageKind,
      url: window.location.href,
      title: document.title || "",
      videoId: detection.videoId,
      captionAvailability: captionAvailable ? "available" : "unavailable",
      source,
      overlayMode: overrides.overlayMode || (source === "audio" ? "inline-overlay" : "hidden"),
      status: overrides.status || (source === "audio" ? "privacy-required" : "caption-primary"),
      capabilities: source === "audio"
        ? [
            captionAvailable ? "captions-available" : "captions-unavailable",
            "audio-translation-beta",
            "video-audio-translation",
            "selection-fallback",
          ]
        : ["captions-available", "video-caption-overlay", "audio-translation-beta", "selection-fallback"],
      activeSegment: source === "audio"
        ? {
            pageId,
            audioSegmentId,
            videoId: detection.videoId,
            source: "audio",
            sourceText: overrides.sourceText || "",
            translatedText: overrides.translatedText,
            sourceLanguage: overrides.sourceLanguage || "English",
            targetLanguage: overrides.targetLanguage || "简体中文",
            capturedAt: updatedAt,
          }
        : undefined,
      failureReason: overrides.failureReason || (source === "caption" ? "caption-primary" : undefined),
      message: overrides.message || (source === "audio"
        ? "听音翻译 Beta 会在你确认后识别当前视频音频。"
        : "字幕可用，优先使用字幕翻译。"),
      updatedAt,
    };
  };
  const postVideoAudioState = (state, force = false) => {
    if (!state) {
      return false;
    }
    const signature = [
      state.pageKind,
      state.videoId || "",
      state.source,
      state.status,
      state.activeSegment?.audioSegmentId || "",
      state.activeSegment?.sourceText || "",
      state.activeSegment?.translatedText || "",
      state.failureReason || "",
    ].join(":");
    if (!force && signature === lastVideoAudioSignature) {
      return false;
    }
    lastVideoAudioSignature = signature;
    if (state.source === "audio" && state.status !== "privacy-required" && state.status !== "caption-primary") {
      applyVideoCaptionOverlayState(state);
    }
    postBridgeEvent("video.audio.state.changed", state, {
      requestId: "video-audio-state-" + (state.activeSegment?.audioSegmentId || sessionId),
      pageId,
    });
    if (state.quota) {
      postBridgeEvent("video.audio.quota.changed", state.quota, {
        requestId: "video-audio-quota-" + sessionId,
        pageId,
      });
    }
    return true;
  };
  const requestVideoAudioTranslation = (config = {}) => {
    const state = buildYouTubeVideoAudioState({
      source: "audio",
      status: config.status || "privacy-required",
      sourceLanguage: config.sourceLanguage,
      targetLanguage: config.targetLanguage,
      manualAudioSelection: true,
      captionQuality: config.captionQuality,
      captionText: config.captionText,
      message: config.message,
    });
    return postVideoAudioState(state, true);
  };
  const syncVideoCaptionState = (force = false) => {
    // A5 / A7.2：非视频页（含 YouTube 整站非视频页与非 YouTube 页面）不产字幕状态、
    // 不渲染 overlay；切换到非视频页时清除任何残留 surface 并重置字幕轨状态。
    if (!detectYouTubePage().isVideoPage) {
      removeVideoCaptionSurfaces();
      resetVideoCaptionTrack();
      lastVideoAudioSignature = "";
      return false;
    }
    // A1 / A3 / A4：视频页——确保已读取并解析视频自带字幕轨（异步同源 fetch json3），
    // 并装配 timeupdate 监听（按 currentTime 时间同步当前句）。
    installVideoTimeUpdateListener();
    ensureVideoCaptionTrackLoaded().then((hasLines) => {
      if (hasLines) {
        const loadedVideo = document.querySelector("video");
        const loadedTime = loadedVideo && typeof loadedVideo.currentTime === "number" ? loadedVideo.currentTime : 0;
        syncActiveCaptionLine(loadedTime, true);
      } else if (videoCaptionTrackUnavailable) {
        // A6：无字幕轨则降级（caption-unavailable）+ 听音 Beta 入口仍可被 native 调起。
        const fallbackState = buildYouTubeVideoCaptionState({ sourceText: "", failureReason: "caption-unavailable" });
        postVideoCaptionState(fallbackState, true);
        postVideoAudioState(buildYouTubeVideoAudioState(), true);
      }
    });
    // 立即按当前已有字幕序列同步一次当前句（首取尚未就绪时回退 DOM 兜底，等 fetch 回调补发）。
    const video = document.querySelector("video");
    const currentTime = video && typeof video.currentTime === "number" ? video.currentTime : 0;
    const state = videoCaptionLines.length
      ? buildYouTubeVideoCaptionState(buildCaptionLineOverrides(findActiveCaptionLine(videoCaptionLines, currentTime)))
      : buildYouTubeVideoCaptionState();
    const postedCaption = postVideoCaptionState(state, force);
    if (state && state.captionAvailability === "unavailable" && videoCaptionTrackUnavailable) {
      postVideoAudioState(buildYouTubeVideoAudioState(), force);
    }
    return postedCaption;
  };
  const handleYouTubeRouteChange = () => {
    // A4.2 / A5：SPA 前端路由切换后重判页面类型；切视频时丢弃上一个视频字幕轨序列并重置
    // 去重签名 + 解绑旧 timeupdate（视频元素会被 SPA 替换），再重新同步当前视频字幕。
    resetVideoCaptionTrack();
    videoTimeUpdateBound = false;
    syncVideoCaptionState(true);
  };
  const installYouTubeRouteListeners = () => {
    // A4.1：仅在 YouTube 整站注入路径包裹 History API + 监听 popstate；A4.3：不改变
    // 非 YouTube 通用文本网页行为（非 YouTube 直接返回，不安装监听）。
    if (!detectYouTubePage().isYouTube || window.__agentEnglishYouTubeRouteHooked) {
      return;
    }
    window.__agentEnglishYouTubeRouteHooked = true;
    const originalPushState = history.pushState.bind(history);
    const originalReplaceState = history.replaceState.bind(history);
    history.pushState = function (...args) {
      const result = originalPushState(...args);
      handleYouTubeRouteChange();
      return result;
    };
    history.replaceState = function (...args) {
      const result = originalReplaceState(...args);
      handleYouTubeRouteChange();
      return result;
    };
    window.addEventListener("popstate", handleYouTubeRouteChange);
  };

  window.__agentEnglishYouTubeInjection = {
    detectYouTubePage,
    readActiveYouTubeCaptionText,
    applyVideoCaptionOverlayState,
    buildYouTubeVideoCaptionState,
    postVideoCaptionState,
    buildYouTubeVideoAudioState,
    postVideoAudioState,
    requestVideoAudioTranslation,
    syncVideoCaptionState,
    installYouTubeRouteListeners,
    // Phase 8.9：视频自带字幕轨数据读取 / 解析 / 时间同步（注入式单测入口；不出网）。
    readYouTubePlayerResponse,
    parseCaptionTracks,
    selectCaptionTrack,
    buildJson3CaptionUrl,
    parseJson3Captions,
    findActiveCaptionLine,
    captionLineSignature,
    ensureVideoCaptionTrackLoaded,
    installVideoTimeUpdateListener,
    syncActiveCaptionLine,
    resetVideoCaptionTrack,
    getVideoCaptionLines: () => videoCaptionLines,
  };
`;
